services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    restart: unless-stopped
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ./shared/vault-data:/vault/file
      - ./shared/vault-config:/vault/config
      - ./shared/vault/config.sh:/resources/config.sh
      - ./shared/vault/full-access.hcl:/resources/full-access.hcl
      - ./shared/vault/entrypoint.sh:/resources/entrypoint.sh
    cap_add:
      - IPC_LOCK
    command: /bin/sh -c "chmod +x /resources/entrypoint.sh && chmod +x /resources/config.sh && /resources/entrypoint.sh"
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # APP
      - "15672:15672" # UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODE_IP_ADDRESS: "0.0.0.0"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
      
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./shared/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./shared/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
    networks:
      - backend

  otel-collector-contrib:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317" # OTLP gRPC port
      - "4318:4318" # OTLP http port
    volumes:
      - ./shared/otel-config.yaml:/etc/otel/config.yaml
      - ./prom_rw:/etc/prom_rw
    command: ["--config", "/etc/otel/config.yaml"]
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - backend

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./shared/:/etc/loki
    networks:
      - backend

  tempo:
    image: grafana/tempo:latest
    ports:
      - "5317:4317"  # otlp grpc
      - "5318:4318"  # otlp http
      - "3200:3200"  # metrics
    volumes:
      - ./shared/tempo-config.yaml:/etc/tempo-config.yaml
    command: ["-config.file=/etc/tempo-config.yaml"]
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./shared/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command: ["--config.file=/etc/prometheus/prometheus-config.yaml"]
    networks:
      - backend

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  mongo-data:
  redis-data:
  rabbitmq_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
