global using CodeDesignPlus.Net.Exceptions.Guards;
global using CodeDesignPlus.Net.Generator.Attributes;
global using CodeDesignPlus.Net.PubSub.Abstractions;
global using CodeDesignPlus.Net.Security.Abstractions;
global using FluentValidation;
global using Mapster;
global using MapsterMapper;
global using MediatR;
global using C = CodeDesignPlus.Net.Core.Abstractions.Models.Criteria;
global using CodeDesignPlus.Net.Core.Abstractions;
global using CodeDesignPlus.Net.Serializers;
global using NodaTime;
global using CodeDesignPlus.Net.Cache.Abstractions;

global using CodeDesignPlus.Net.Microservice.Application.Order.DataTransferObjects;
global using CodeDesignPlus.Net.Microservice.Domain;
global using CodeDesignPlus.Net.Microservice.Domain.Entities;
global using CodeDesignPlus.Net.Microservice.Domain.Repositories;
global using CodeDesignPlus.Net.Microservice.Domain.Enums;
global using CodeDesignPlus.Net.Microservice.Domain.DataTransferObjects;