name: Publish Generator

on:
  push:
    branches:
    - main
    - rc
    - dev
    - feature/*

env:
  IS_RELEASE: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
  IS_RC: ${{ github.ref == 'refs/heads/rc' }}
  IS_BETA: ${{ github.ref == 'refs/heads/dev' }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      repository-projects: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: SemVer
      id: git-semver
      uses: codedesignplus/semver-git-version@v0.1.10
      with:
        folder: ${{github.workspace}}
        release-branch: 'main'
        release-candidate-branch: 'rc'
        beta-branch: 'dev'
        major-identifier: 'breaking'
        minor-identifier: 'feat'
        prefix: 'v'
        dir-affected: ./
        previous-version: true
        new-version: true

    - name: Print Output
      id: output
      run: |
        echo Previous Tag "${{ steps.git-semver.outputs.previous-tag }}"
        echo Previous Version "${{ steps.git-semver.outputs.previous-version }}"
        echo Previous Version Prefix "${{ steps.git-semver.outputs.previous-version-prefix }}"
        echo New Version "${{steps.git-semver.outputs.new-version}}"
        echo New Version Prefix "${{steps.git-semver.outputs.new-version-prefix}}"

    #   - name: Install dependencies
    #     run: npm ci

    #   - name: Run tests
    #     run: npm test

    #   - name: Set git user
    #     run: |
    #         git config --global user.name "github-actions[bot]"
    #         git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Set version
      run: npm version ${{ steps.git-semver.outputs.new-version }} --no-git-tag-version

    - name: Build
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    #   - name: Publish to GitHub Packages
    #     run: |
    #       npm config set //npm.pkg.github.com/:_authToken ${GITHUB_TOKEN}
    #       npm publish --access public
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Publish to npm
    #     if: github.event.repository.owner.login == 'codedesignplus'
    #     run: |
    #       npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    #       npm publish --access public
    #     env:
    #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


    - name: Push tag
      id: push_tag
      if: env.IS_RELEASE == 'true' || env.IS_RC == 'true' || env.IS_BETA == 'true'
      uses: mathieudutour/github-tag-action@v6.1
      with:
        custom_tag: ${{ steps.git-semver.outputs.new-version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Changelog
      if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: "${{ github.workspace }}/.github/settings/configuration.json"
        fromTag: ${{ steps.git-semver.outputs.previous-version-prefix }}
        toTag: ${{ steps.git-semver.outputs.new-version-prefix }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
      uses: mikepenz/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.git-semver.outputs.new-version-prefix }}
        name: "CodeDesignPlus.Net.Sdk@${{ steps.git-semver.outputs.new-version-prefix }}"
        body: ${{ steps.build_changelog.outputs.changelog }}
        prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'dev') }}
